version: '3'

networks:
  printervendo:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: printervendo
    ports:
      - "8001:80"
    volumes:
      - ../:/var/www/html
      - ./logs:/var/log/docker/nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # privileged: true
    depends_on:
      - php
      - mysql
    networks:
      - printervendo
    restart: always

  php:
    build:
      context: .
      # dockerfile: Dockerfile
    container_name: printervendo_php
    volumes:
      - ../:/var/www/html
    networks:
      - printervendo
    restart: always
  mysql:
    image: mysql:5.7.29
    command: mysqld --sql_mode=""
    container_name: printervendo_db
    restart: always
    environment:
      MYSQL_DATABASE: printervendo
      MYSQL_PASSWORD: mvst2021
      MYSQL_ROOT_PASSWORD: secret456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - printervendo
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql

  # redis:
  #   image: redis:4.0
  #   container_name: worksuite_redis
  #   networks:
  #     - printervendo

  # composer:
  #   image: composer:1.10
  #   working_dir: /app
  #   environment:
  #     SSH_AUTH_SOCK: /ssh-auth.sock
  #   volumes:
  #     - ./:/app
  #     - "$SSH_AUTH_SOCK:/ssh-auth.sock"
  #     - /etc/passwd:/etc/passwd:ro
  #     - /etc/group:/etc/group:ro
  #   command: composer install --ignore-platform-reqs --no-scripts

